# Contents of the file: /janmarg/janmarg/backend/train/config/synthetic.yaml

model:
  name: "efficientnet-b0"
  pretrained: true
  num_classes: 2

training:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 20
  weight_decay: 0.0001
  optimizer: "adam"

data:
  train_data_path: "/path/to/train/data"
  val_data_path: "/path/to/val/data"
  image_size: [224, 224]
  augmentations:
    - type: "random_horizontal_flip"
      probability: 0.5
    - type: "random_rotation"
      degrees: 15

logging:
  log_dir: "./logs/synthetic"
  log_interval: 10

evaluation:
  metrics:
    - "accuracy"
    - "f1_score"
  save_best_model: true
  model_save_path: "./models/synthetic_best.pth"