version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env.template
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    volumes:
      - ../frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: janmarg
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: